config/routes.rb
# This file was generated by Rails...
# frozen_string_literal: true

Rails.application.routes.draw do
  # root on home page
  root to: 'pages#home'

  # different routes
  get 'home', to: 'pages#home'
  get 'contact', to: 'pages#contact'

  resources :candys
  resources :containers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/candy.rb
class Candy < ApplicationRecord
  self.table_name = 'candys'
  # Les colonnes dans la table "candys"
  # t.string "name"
  # t.string "category"
  # t.string "img"
  # t.string "tag"
  # t.string "unity"
  # t.string "newproduct"

  validates :name, presence: true
  # Vous pouvez ajouter d'autres validations selon vos besoins
end

app/models/container.rb
class Container < ApplicationRecord
  self.table_name = 'containers'
  # Les colonnes dans la table "containers"
  # t.string "name"
  # t.string "category"
  # t.string "img"
  # t.string "tag"
  # t.string "dim"
  # t.string "newproduct"

  validates :name, presence: true
  # Vous pouvez ajouter d'autres validations selon vos besoins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/candys_controller.rb
class CandysController < ApplicationController
  def index
    @candys = Candy.all

    if params[:search].present?
      @candys = Candy.where('name LIKE ?', "%#{params[:search]}%")
    end

    if params[:newproduct].present? && params[:newproduct] == 'true'
      @candys = @candys.where(newproduct: 'true')
    end

    if params[:category].present?
      @candys = Candy.where(category: params[:category])
    end
  end
end

app/controllers/containers_controller.rb
class ContainersController < ApplicationController
  def index
    @containers = Container.all

    if params[:search].present?
      @containers = @containers.where('name ILIKE ?', "%#{params[:search]}%")
    end

    if params[:newproduct].present? && params[:newproduct] == 'true'
      @containers = @containers.where(newproduct: 'true')
    end

    if params[:category].present?
      @containers = @containers.where(category: params[:category])
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @candys = Candy.where(newproduct: 'true')
    @containers = Container.where(newproduct: 'true')
  end

  def contact; end

  def candys; end

  def containers; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candys_helper.rb
module CandysHelper
end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/candys/index.html.erb
<div class="container-candy">
  <div class="form-candy">
    <%= image_tag "logos/SaMass-Full-Color.svg" %>
    <%= form_tag candys_path, method: :get, class: "search-form-candy" do %>
      <%= text_field_tag :search, params[:search], placeholder: "Rechercher une confiserie" %>
      <%= submit_tag "Rechercher" %>
    <% end %>

    <%= form_tag candys_path, class: "form-search-category", method: :get do %>
      <div class="container-gallery-form">
        <div class="mobile-dropdown">
          <ul id="categoryOptions" class="category-options-candy">
            <li class="category-li-candy">
              <%= button_tag type: "button", class: "category-button bl-txt", data: { newproduct: 'true' } do %>
                Nouveaux Produits
              <% end %>
              <%= hidden_field_tag :newproduct, params[:newproduct] %>
            </li>
            <% Candy.distinct.pluck(:category).each do |category| %>
              <li class="category-li-candy">
                <%= button_tag type: "button", class: "category-button", data: { category: category } do %>
                  <%= category %>
                <% end %>
              </li>
            <% end %>
          </ul>
          <%= hidden_field_tag :category, params[:category] %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="container-gallery-candys">
    <% @candys.each do |candy| %>
    <div class="cards-gallery-candys">
      <div class="gallery-candys">
        <div class="container-size-img">
          <%= image_tag "confiseries/#{candy.img}", class: "img-candy", alt:"#{candy.tag}" %>
        </div>
        <div class="container-size-text">
          <span class="span-candy-name"><img class="img"><%= candy.name %></span>
          <span class="span-candy-category"><%= candy.category %></span>
          <span class="span-candy-unity">Unité: <%= candy.unity %></span>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/containers/index.html.erb
<div class="container-container">
  <div class="form-container">
    <%= image_tag "logos/SaMass-Full-Color.svg" %>
    <%= form_tag containers_path, method: :get, class: "search-form" do %>
      <%= text_field_tag :search, params[:search], placeholder: "Rechercher un contenant" %>
      <%= submit_tag "Rechercher", class: "btn btn-primary" %>
    <% end %>
    <%= form_tag containers_path, class: "form-search-category", method: :get do %>
      <div class="container-gallery-form">
        <div class="form-search">
          <ul id="categoryOptions" class="category-options">
            <li class="category-li">
              <%= button_tag type: "button", class: "category-button bl-txt", data: { newproduct: 'true' } do %>
                Nouveaux Produits
              <% end %>
              <%= hidden_field_tag :newproduct, params[:newproduct], id: "newproductField" %>
            </li>
            <% Container.distinct.pluck(:category).each do |category| %>
              <li class="category-li">
                <%= button_tag type: "button", class: "category-button", data: { category: category } do %>
                  <%= category %>
                <% end %>
              </li>
            <% end %>
          </ul>
          <%= hidden_field_tag :category, params[:category] %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="container-gallery-container">
    <% @containers.each do |container| %>
      <div class="cards-gallery-container">
        <div class="gallery-container">
          <div class="container-size-img">
            <%= image_tag "contenants/#{container.img}", class: "img-container", alt:"#{container.tag}" %>
          </div>
          <div class="container-size-text">
            <span class="span-container-name"><%= container.name %></span>
            <span class="span-container-category"><%= container.category %></span>
            <span class="span-container-dim">Dimension : <%= container.dim %></span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Les saveurs de Massalia</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- favicon of massalia  -->
    <%= favicon_link_tag "logos/SaMass-Full-Color.svg", rel: "icon", type: "svg" %>
    <!-- SCSS link -->
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <!-- JS -->
    <%= javascript_include_tag 'application' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Shantell+Sans:ital@1&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render "components/navbar" %>
    <%= yield %>
    <%= mail_to "bertrand.vanden.neste@gmail.com", class: "phone" do %>
      <%= image_tag "logos/SaMass-Full-Color-1.svg" %>
    <% end %>
    <%= render "components/footer" %>
  </body>
</html>

app/views/pages/contact.html.erb
<div class="container-blocks-contact">
  <div class="block-contact">
    <div class="vignette-logo-mobile">
      <%= image_tag "logos/SaMass-Full-Color.svg" %>
    </div>
    <div class="vignette-profil">
      <div class="background-vignette-profil-1">
        <%= image_tag "profil/ameer-basheer-ABuzWPku1Ug-unsplash-removebg-preview.png", class: "avatar-large-1", alt: "avatar-large" %>
        <div class="vignette-text">
          <span>Philippe DUFOSSE</span>
          <span>06 11 23 69 47</span>
        </div>
      </div>
    </div>
    <div class="vignette-logo">
      <%= image_tag "logos/SaMass-Full-Color.svg" %>
    </div>
    <div class="vignette-profil">
      <div class="background-vignette-profil">
        <div class="vignette-text">
          <span>Hana MECHAIGUI</span>
          <span>06 51 50 46 43</span>
        </div>
        <%= image_tag "profil/sofia-mQtcrK22CN8-unsplash-removebg-preview.png", class: "avatar-large", alt: "avatar-large" %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container-blocks">
  <% if @candys.any? %>
    <div class="news-banner">
      <% @candys.each do |candy| %>
        <div class="cards-gallery-news">
          <div class="gallery-news">
            <%= image_tag "logos/icons8-nouveau-64.png", class: "img-news", alt:"#{candy.tag}" %>
            <%= image_tag "confiseries/#{candy.img}", class: "img", alt:"#{candy.tag}" %>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
  <% end %>
  <div class="banner">
    <div id="container-text" class="container-text">
      <div class="logo-animation">
        <%= image_tag "logos/SaMass-Full-Color-1.svg", class:"logo logo-1"%>
        <%= image_tag "logos/SaMass-Full-Color-2.svg", class:"logo logo-3"%>
        <%= image_tag "logos/SaMass-Full-Color-3.svg", class:"logo logo-3"%>
        <%= image_tag "logos/SaMass-Full-Color-4.svg", class:"logo logo-3"%>
      </div>
      <h1 class="accroche animation-txt">Colis Gastronomiques ! Goûters de Noël ! Objets Publicitaires ! Cadeaux !</h1>
      <h2 class="animation-txt">Bienvenue chez Massalia, une entreprise passionnée par la création de délicieux goûters artisanaux en partenariat avec des Établissements et Services d'Aide par le Travail (ESAT). Notre entreprise allie la gourmandise à l'inclusion sociale, offrant une expérience unique à nos clients tout en favorisant l'emploi des personnes en situation de handicap.</h2>
    </div>
  </div>
  <div class="collab">
    <h2 class="animation-txt">Nos collaborateurs</h2>
    <div class="collab-logos">
      <div class="collab-logos-container" >
        <%= image_tag "logos/logo_ari_1.png", class:"logo-animation" %>
      </div>
      <div class="collab-logos-container">
        <%= image_tag "logos/logo_unapei_1.png", class:"logo-animation" %>
      </div>
    </div>
    <p class="animation-txt">Chez Massalia, nous croyons en la puissance de la diversité et de l'inclusion. C'est pourquoi nous avons établi des partenariats solides avec des ESAT locaux, qui sont des structures dédiées à l'accompagnement et à la formation professionnelle de personnes en situation de handicap. Grâce à ces partenariats, nous avons la chance de travailler avec des artisans talentueux qui apportent leur savoir-faire unique à la création de nos goûters exceptionnels.</p>
  </div>
  <div class="collab-populaire">
    <h2 class="animation-txt">Chez nous pas de gaspillage</h2>
    <%= image_tag "logos/logo_secours_populaire.png", class:"logo-animation" %>
    <p class="animation-txt">Chaque fin d’année nous redistribuons gracieusement les confiseries invendues et en faisons don au Secours Populaire et divers Comités d’Entreprises qui peuvent ainsi organiser des loteries pour leur personnel.</p>
  </div>
</div>

app/views/pages/mentions_legales.erb
<h2>Mentions Légales</h2>

<p><strong>Éditeur du site :</strong></p>
<p>Nom de l'éditeur : Les Saveurs de Massalia<br>
Raison sociale : Les Saveurs de Massalia SARL<br>
Adresse : 68 Avenue de la Figone, 13012 Marseille, France<br>
Téléphone : +33 4 91 23 45 67<br>
Email : contact@les-saveurs-de-massalia.com</p>

<p><strong>Hébergeur :</strong></p>
<p>Nom de l'hébergeur : OVH<br>
Adresse : 2 Rue Kellermann, 59100 Roubaix, France<br>
Téléphone : +33 9 72 10 10 07</p>

<p><strong>Responsable de la publication :</strong></p>
<p>Nom du responsable : Jean Dupont<br>
Email : jean.dupont@les-saveurs-de-massalia.com</p>

<p><strong>Numéro d'identification :</strong></p>
<p>SIRET : 123 456 789 00010<br>
Numéro de TVA : FR 00 123456789</p>

<p><strong>Propriété Intellectuelle :</strong></p>
<p>Tout le contenu du site (textes, images, vidéos) est protégé par le droit d'auteur. Toute reproduction est interdite sans autorisation préalable.</p>

<p><strong>Conditions d'utilisation :</strong></p>
<p>En utilisant ce site, vous acceptez les <a href="conditions-utilisation.html">conditions générales d'utilisation</a> disponibles ici.</p>

<p><strong>Déclaration CNIL :</strong></p>
<p>Ce site a fait l'objet d'une déclaration auprès de la CNIL sous le numéro 1234567.</p>

app/views/pages/politiques_entreprises.erb
<h2>Politique de Confidentialité</h2>

<p><strong>Informations Collectées :</strong> Nous collectons des informations personnelles comme le nom, l'email, et l'adresse IP via des formulaires et des cookies.</p>

<p><strong>Utilisation des Données :</strong> Vos données sont utilisées pour le service client, les communications marketing, et l'amélioration de notre site. La base légale du traitement est le consentement.</p>

<p><strong>Partage des Données :</strong> Nous partageons vos données avec des partenaires de confiance et des prestataires de services. Nous prenons des mesures pour garantir la sécurité des transferts de données hors UE.</p>

<p><strong>Droits des Utilisateurs :</strong> Vous avez le droit d'accéder, de rectifier, d'effacer vos données, de limiter leur traitement, et de vous opposer à leur utilisation. Pour exercer ces droits, contactez-nous à dpo@les-saveurs-de-massalia.com.</p>

<p><strong>Conservation des Données :</strong> Vos données sont conservées pendant 2 ans ou selon les exigences légales. Nous déterminons cette durée en fonction de la nature des données et des besoins de traitement.</p>

<p><strong>Sécurité des Données :</strong> Nous mettons en œuvre des mesures de sécurité pour protéger vos informations personnelles contre les accès non autorisés et les divulgations.</p>

<p><strong>Cookies :</strong> Nous utilisons des cookies pour analyser notre trafic et personnaliser votre expérience. Vous pouvez gérer vos préférences de cookies dans les paramètres de votre navigateur.</p>

<p><strong>Contact pour la Protection des Données :</strong> Si vous avez des questions, contactez notre DPO à dpo@les-saveurs-de-massalia.com.</p>